import {
  MessageSquareText,
  Handshake,
  TerminalSquare,
  HelpCircle,
  Rocket,
  Wrench,
  Target,
  ClipboardList,
  Sparkles,
  Brain,
  Cog,
  Lock,
  Clock,
  Wallet,
  Bot,
  Boxes,
  PenLine,
  ShieldCheck,
  Puzzle,
  Frown,
  Eye,
  Flame,
  Hourglass,
  Coffee,
  FilePen,
  Code2,
  Search,
  BarChart3,
  Lightbulb,
  Headphones,
  FolderKanban,
  Hand,
  Compass,
  MousePointerClick,
  Check,
  X,
  Mail,
  Newspaper,
  Gift,
  HandCoins,
  XCircle,
  type LucideIcon,
} from "lucide-react";

const map: Record<string, LucideIcon> = {
  "mode_excited:chat": MessageSquareText,
  "mode_excited:cowork": Handshake,
  "mode_excited:code": TerminalSquare,
  "mode_excited:undecided": HelpCircle,

  "role:founder": Rocket,
  "role:builder": Wrench,
  "role:consultant": Target,
  "role:ops": ClipboardList,
  "role:other": Sparkles,

  "blocker:use_cases": Brain,
  "blocker:setup": Cog,
  "blocker:trust": Lock,
  "blocker:time": Clock,
  "blocker:cost": Wallet,

  "next_topic:agents": Bot,
  "next_topic:tools": Boxes,
  "next_topic:content": PenLine,
  "next_topic:privacy": ShieldCheck,
  "next_topic:workflows": Puzzle,

  "take_on_ai:skeptical": Eye,
  "take_on_ai:curious": Flame,
  "take_on_ai:overwhelmed": Hourglass,
  "take_on_ai:no_time": Coffee,

  "use_cases:writing": FilePen,
  "use_cases:coding": Code2,
  "use_cases:research": Search,
  "use_cases:analysis": BarChart3,
  "use_cases:brainstorm": Lightbulb,
  "use_cases:customer": Headphones,
  "use_cases:admin": FolderKanban,
  "use_cases:other": Sparkles,

  "aha_mode:chat": MessageSquareText,
  "aha_mode:cowork": Handshake,
  "aha_mode:code": TerminalSquare,
  "aha_mode:none": Frown,

  "active_project:building": Rocket,
  "active_project:planning": Compass,
  "active_project:curious": Lightbulb,
  "active_project:no": Hand,

  "wants_chat:yes": Check,
  "wants_chat:no": X,

  "interests:next_workshop": Mail,
  "interests:newsletter": Newspaper,
  "interests:playbook": Gift,
  "interests:consulting": HandCoins,
  "interests:none": XCircle,
};

export function iconFor(questionId: string, value: string): LucideIcon {
  return map[`${questionId}:${value}`] ?? MousePointerClick;
}
